### ISSUE TITLE
Use Map instead of Object

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-node#148]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Objects_and_maps_compared

There's a lot of locations in the codebase where we use an object where a map is more appropriate.

**Comment by black-adder** [comment]
I made an attempt but got `ReferenceError: Map is not defined` in node 0.10.0. My guess it's a relatively new thing? @tiffon

**Comment by tiffon** [comment]
Well, 0.10 is over four years old[0], pretty rough constraint. Definitely
closes a lot of doors, using Map being one of them.

In that case, a few of my suggestions may have missed the Mark.

0: https://en.m.wikipedia.org/wiki/Node.js#Releases

**Comment by yurishkuro** [comment]
we cannot break 0.10 compat at this time There may exist some polyfills for Map.

**Comment by tiffon** [comment]
There is the babel polyfill <https://babeljs.io/docs/usage/polyfill/>, which
includes core-js
<https://github.com/zloirock/core-js#ecmascript-6-collections> (with
collections, support), but it comes with a word of warning:

This will emulate a full ES2015+ environment and is intended to be used in
an application rather than a library/tool.
