### ISSUE TITLE
Support callback in udpSender.flush

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#157]
Right now there is no way to use Jaeger client in script-like apps (like the [OpenTracing tutorial for Node.js](https://github.com/yurishkuro/opentracing-tutorial/tree/master/nodejs)) because when the app exists the reporter may still have span buffered and they don't get flushed, even if the app calls `tracer.close()`.

The RemoteReporter and UDPSender are written in non-idiomatic style for JS/Node where UDPSender returns values from its append/flush method instead of using callbacks. It would be best to re-implement their interfaces to use callbacks for reporting the results. Then the reporter's own `close()` method make make sure that the UDP packet is actually flushed before returning.

**Comment by MarckK** [comment]
A first attempt to wrap UDPSender flush method in a Promise has thrown up a number of issues: It compiles fine; however, I do get Flow errors, and some tests break, since I am returning a promise value and not a return value (for example: udp sender should flush with no spans returns false for error, and 0: AssertionError: expected undefined to equal false).

Additionally, when I compile the change in my local dev environment and use the edited tracer (for example, with the nodejs tutorial), it seems like `let numSpans: number = this._batch.spans.length;` can no longer access the `this._batch` property: I get the following error: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_batch' of undefined

Here's what I've done to the UDPSender flush method: 
```js
flush(): SenderResponse {
    return new Promise(function(resolve, reject) {
      let numSpans: number = this._batch.spans.length;
      if (numSpans == 0) {
        return resolve({ err: false, numSpans: 0 });
      }

      let bufferLen = this._totalSpanBytes + this._emitSpanBatchOverhead;
      let thriftBuffer = new Buffer(bufferLen);
      let writeResult = this._agentThrift.Agent.emitBatch.argumentsMessageRW.writeInto(
        this._convertBatchToThriftMessage(this._batch),
        thriftBuffer,
        0,
      );

      if (writeResult.err) {
        this._logger.error(`error writing Thrift object: ${writeResult.err}`);
        return reject({ err: true, numSpans: numSpans });
      }

      // Having the error callback here does not prevent uncaught exception from being thrown,
      // that's why in the constructor we also add a general on('error') handler.
      this._client.send(
        thriftBuffer,
        0,
        thriftBuffer.length,
        this._port,
        this._host,
        (err, sent) => {
          if (err) {
            this._logger.error(
              `error sending spans over UDP: ${err}, packet size: ${
                writeResult.offset
              }, bytes sent: ${sent}`,
            );
          }
        },
      );
      this._reset();

      return resolve({ err: false, numSpans: numSpans });
    });
  }
```

**Comment by yurishkuro** [comment]
you probably need to capture `this` to a local var so that it's still accessible from the closure of promises.

the flow errors are expected since you changed the return type of the method from SenderResponse to Promise. It would require redefining a bunch of interfaces.

For this reason, and also to avoid adding extra dependencies, my preference is to have this feature added without promises, but with a callback approach.

**Comment by geovanisouza92** [comment]
Any updates on this?

**Comment by phal0r** [comment]
I would vote for Promises or async/await notation. To stick to callbacks just to avoid refactoring doesn't seem the way to go, since Promises and async/await allow for better code than passing callbacks around.

I know this is easy to say from an outside point if view, but in the long run these are the better patterns in my opinion.

**Comment by yurishkuro** [comment]
My concern is not with the refactoring, but (a) with backwards compatibility, and (b) with adding an arbitrary dependency, since promises are not a standard.

**Comment by phal0r** [comment]
Regarding
(a) that would mean a new major release according to semver, but should in general not be a problem
(b) Promises are part of the ES6 standard and not a dependency (anymore). All major browsers (except IE of course ;) ) and node support them. Also native browser apis, like getUserMedia, move from callbacks to Promises. 

I could not find information on what platforms this module should support, but since it's called `jaeger-client-node` I assume it's only node and therefore support for Promises is not an issue for any LTS versions.

**Comment by yurishkuro** [comment]
Major semver bump can be a major problem in a large org like ours, since instead of getting automatic updates from minor bumps several hundred engineers need to change their deps manually. It can be mitigated to a certain degree by have internal wrappers, but still, major bump for a minor nice to have feature is not something to be taken lightly.

However, I don't recall if we actually *have* public APIs taking callbacks in the lib, so using promises is a possibility. I definitely like then better semantically. 

How are they backported to ES5?

The current target if this lib is Node, but we want to extend it to support browsers.

**Comment by geovanisouza92** [comment]
According to https://github.com/nodejs/Release, Node 0.10 and 0.12 are in the end of its life, and according to http://node.green/, Node 4 already have Promises natively for quite some time.

I don't think that this is a problem.

**Comment by phal0r** [comment]
What I have seen from browser modules, that use promises is, that they state it in their Readme and advise to include a promise shim for the project, that wants to use such a module AND wants to support IE.

I would add this feature to the next major milestone, along with other improvements/refactorings to justify a major bump. I don't know if this fits your versioning policy though.

**Comment by MarckK** [comment]
If we did want to use Promises, with backwards compatibility, it's possible we could use [babel-polyfill](https://babeljs.io/docs/usage/polyfill/).

**Comment by yurishkuro** [comment]
We decided to go with the callback to avoid introducing extra dependencies (like promises, which are not native in older Node versions) and additional memory allocations required for promises.
