### ISSUE TITLE
husky should not be an optional dependency

### ISSUE THREAD

**Issue by eseliger** [jaegertracing/jaeger-client-node#232]
`optionalDependencies` are being installed for consumers of the library as well, resulting in having husky installed in my project and checking my commit messages now. I think it should better be a `devDependency` as well.

**Comment by MarckK** [comment]
Yes, you are correct that npm installs all dependencies (dev and optional) by default with the basic npm install command. 

Because of our test set-up with Travis we can't have husky be a regular `devDependency`.

You can leave optional dependencies out upon installation with the `--no-optional` flag.

But, yes, we'll need to make husky be an optional `devDependency`, not an optional `dependency`.

**Comment by yurishkuro** [comment]
> Because of our test set-up with Travis we can't have husky be a regular devDependency.

why is that?

**Comment by yurishkuro** [comment]
3.9.1 released that removes husky dependency until we find a way to use it safely

**Comment by MarckK** [comment]
Not really. It's such a pain. 
I'm attempting to write an install script for it that would install husky as a `devDependency` on node >= 4.  

Something like:
```
"install": "if [[ $(node -v | sed 's/v//' >= 4) ]]; then npm install husky --save-dev; fi",
```
But I'm getting errors: 
`sed: 4: No such file or directory`

Or second approach:
```
"install": "if [ '`node -v | sed 's/v//'`' -gt 4 ]; then npm install husky --save-dev; fi",
```
`sh: line 0: [: `node -v | sed s/v//`: integer expression expected`

Tips/opinions appreciated.

**Comment by tiffon** [comment]
I've given it a shot uninstalling husky before the `install` step in CI on #234.
