### ISSUE TITLE
Support Prometheus client

### ISSUE THREAD

**Issue by eundoosong** [jaegertracing/jaeger-client-node#253]
## Requirement - what kind of business use case are you trying to solve?
It will be better to provide prometheus client for metrics monitoring, as the other clients.
I'm going to use [prom-client](https://www.npmjs.com/package/prom-client), which seems the most popular in node.

## Problem - what in Jaeger blocks you from solving the requirement?
Currently, all metrics call in node client look like this.
```node 
this._metrics.spansFinished.increment(1);
```
The name of increment method in prom-client is **inc**, which is differnt from node client(**increment**).
So increment method should be provided as kind of wrapper so that inc is called inside, IMO which makes code redundant.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
To simplify, I would suggest removing method and call like this.
```node
this._metrics.spansFinished(1);
```
Then we just return an increment function in createCounter/Gauge (It's the same way as python)
```node
createCounter(name, tags) {
  // .... Implementation ....
  var increment = val => {
      this.counter.inc(val)
  }
  return increment
}
```

**Comment by yurishkuro** [comment]
@eundoosong thanks for looking at prom support. 

The abstraction that Jaeger provides for metrics is at the metrics factory level. We don't want to change the factory interface. So whichever other metrics client we plug in, eg prom, it is still going to need a wrapper to adapt to the factory interface, so that it could be used to construct the Metrics object. Whether that object exposes objects with Inc() methods or exposes functions directly, it is an internal implementation detail of Jaeger client. 

I wouldn't mind the change you are proposing, but I don't think it helps with prom client. And technicially, since we didn't place Metrics class under "internal" package it is currently a part of the public API of this library, so best to avoid changing it.

**Comment by eundoosong** [comment]
@yurishkuro 
>since we didn't place Metrics class under "internal" package it is currently a part of the public API of this library

I agree we don't need to change Public API for this feature.
Let me keep the factory interface as is.
Thanks for clarifying.
