### ISSUE TITLE
Sampling by custom fields in the request

### ISSUE THREAD

**Issue by sundarkvp** [jaegertracing/jaeger-client-node#260]
The current set of sampling strategies are all,  rate based,  probabilistic based,  per operation and those samplers takes random requests.    

We would like to sample the traces based on specific value in the incoming request.    This will help us to enable traces for the all the requests received from a particular caller.  

I am not sure it is achievable with current set of sampling mechanisms.    Do you have any plans to provide such sampler ?   Or    Is it possible to add our own custom sampler which implements the common sampler interface which can be used in Tracing Config ?   Please advise.

**Comment by yurishkuro** [comment]
This is something we are also considering for our internal needs. There are two issues with custom sampling:
  1. it is impossible to do inside the tracer implementation, because when applications are instrumented with OpenTracing API, the only data the tracer gets in the callbacks is the request headers (sometimes not even all headers). So if your adhoc sampling would be based on headers only, something can be done about it in the tracer, but if you want to based decisions on the actual request payloads, the tracer simply doesn't have access to those, and it's unlikely that OpenTracing will be extended to provide such access since the data structures would be highly dependent on specific RPC framework used.
  1. you can definitely implement your sampling logic outside of the default OpenTracing instrumentation, where you will have access to all your custom payloads and can make appropriate decisions. The issue is how to tell the tracer that you want a particular request sampled. It's certainly possible today to simply hack it, i.e. directly access the bits in the span context that control sampling, but it's very dirty and creates conflicts with other mechanisms that exist in the tracer like throttling, etc. You can also use the `sampling.priority` span tag to affect the tracer's sampling but in the current Jaeger implementation you can only use it to raise the debug flag, which also has other implications (e.g. debug spans are typically exempted from load shedding in the collector, so an abuse of that flag may overload the tracing backend).

My advice would be for you to try something out first, even in a hacky way, and report back with what you will have learned, it will be a lot easier to discussion having concrete examples.
